name: 'Terraform'

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      TF_BACKEND_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}       
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name : Play with current dir 
        id: play_dir
        run: |
          ls        
      # Initialize a neww or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init -upgrade -backend-config="access_key=$TF_BACKEND_ACCESS_KEY"
      - name: Terraform Plan and Apply
        run: |
          for tfvars_file in *.tfvars; do
            echo "Running terraform plan for $tfvars_file"
            terraform plan -var-file="$tfvars_file" -input=false

            echo "Running terraform apply for $tfvars_file"
            terraform apply -var-file="$tfvars_file" -auto-approve -input=false
          done
              
