name: 'LeverageMatrix'

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  generate-matrix:
    name: 'Generate Matrix'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find-tfvars.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Find .tfvars files
        id: find-tfvars
        run: |
          # Find all .tfvars files
          # tfvars_files=$(find . -name "*.tfvars" | tr '\n' ' ' | sed 's/ *$//')
          tfvars_files=$(find . -name "*.tfvars" | jq -R -s -c 'split(" ") | map(select(length > 0))')

          echo "::set-output name=matrix::$tfvars_files"
      
      - name : Double check value of tfvars
        id : ls-tfvars
        run: |
          echo "Matrix JSON: ${{ steps.find-tfvars.outputs.matrix }}"
  infradeploy:
    name: 'infradeploy'
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tfvars_file: ${{ (needs.generate-matrix.outputs.matrix) }}
    steps: 
      - name : Double check value of tfvars
        id : lstvars
        run: |
          echo "Matrix JSON: ${{ matrix.tfvars_file }}"
      


