name: 'LeverageMatrix'

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  generate-matrix:
    name: 'Generate Matrix'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find-tfvars.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Find .tfvars files
        id: find-tfvars
        run: |
          # Find all .tfvars files
          tfvars_files=$(find . -name "*.tfvars" -print0 | xargs -0 echo)
          if [ -z "$tfvars_files" ]; then
            echo "No .tfvars files found"
            tfvars_files="[]"
          else
            tfvars_files=$(echo "$tfvars_files" | jq -R -s -c 'split(" ") | map(select(length > 0))')
          fi
          echo "Matrix JSON: $tfvars_files"
          echo "::set-output name=matrix::$tfvars_files"

      - name: Set Matrix
        id: set-matrix
        run: echo "::set-output name=matrix::${{ steps.find-tfvars.outputs.matrix }}"
